[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
# TERM = "alacritty"
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5

opacity = 0.9
blur = true
# decorations = "Buttonless"

option_as_alt = "Both"

[font]
normal.family = "FiraCode Nerd Font"
normal.style = "Regular"
size = 12

